### ISSUE TITLE
Fullchain certificate not loaded

### ISSUE THREAD

**Issue by GermanBluefox** [Daplie/le-store-certbot#2]
Why the fullchain certificate was removed?

https://github.com/Daplie/le-store-certbot/blob/master/index.js#L206

Without fullchain.pem the Let'sEncrypt certificate is not trusted.

**Comment by coolaj86** [comment]
Because it's superfluous and other plugins don't require it.

```js
var fullchain = certs.cert + cert.chain;
```

or from the shell

```sh
cat cert.pem chain.pem > fullchain.pem
```

**Comment by GermanBluefox** [comment]
Thank you.
