### ISSUE TITLE
Use proper home directory on Windows

### ISSUE THREAD

**Issue by CaselIT** [Daplie/le-store-certbot#3]
Hi,

I'm testing letsencrypt on windows and I have found this issue:
In windows the `~` directory is not defined so the default configuration will use `./~/letsencrypt` in the current folder instead of using `letsencrypy` in the home folder.
Nodejs does have the [appropriate function](https://nodejs.org/api/os.html#os_os_homedir) to return the home directory so it could be used instead of `~`.

Thanks

**Comment by coolaj86** [comment]
How were you using this module? Most of the code that uses this directly was updated to call `.replace(/~/, os.homedir())`, but something may have slipped through the cracks.

**Comment by CaselIT** [comment]
I'm not directly using it. I use greenlock-express that makes use of this library.
I've not tested if the latest version still has this problem though.

Regardless, shouldn't be better to change 
```js
configDir: [ '~', 'letsencrypt', 'etc' ].join(path.sep)                     // /etc/letsencrypt/
, logsDir: [ '~', 'letsencrypt', 'var', 'log' ].join(path.sep)                // /var/log/letsencrypt/
, workDir: [ '~', 'letsencrypt', 'var', 'lib' ].join(path.sep) // /var/lib/letsencrypt/
```
to
```js
configDir: [ os.homedir(), 'letsencrypt', 'etc' ].join(path.sep)                     // /etc/letsencrypt/
, logsDir: [ os.homedir(), 'letsencrypt', 'var', 'log' ].join(path.sep)                // /var/log/letsencrypt/
, workDir: [ os.homedir(), 'letsencrypt', 'var', 'lib' ].join(path.sep) // /var/lib/letsencrypt/
```
here, instead of using `.replace(/~/, os.homedir())`?

**Comment by coolaj86** [comment]
I did a quick grep through the other code and I don't think there would be any harm in doing that.

Let's continue the conversation over here:

* https://git.daplie.com/Daplie/le-store-certbot/issues/5

If you make a PR, just comment with it here too so we get it in when testing:

* https://git.daplie.com/Daplie/node-greenlock/issues/81

**Comment by CaselIT** [comment]
Ok I'll add a pr later today

**Comment by CaselIT** [comment]
Added PR (or MR in glab) to fix this.
I'm closing it here on github
